spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongousr
      password: mon35G00
      database: pap-databse
      port: 27017
      host: localhost
  main:
    web-application-type: none
  application:
    name: pap21zZ25
logging:
  file:
    name: logback-spring.xml
#  Show queries in logs
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG