spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongousr
      password: mon35G00
      database: pap-databse
      port: 27017
      host: localhost
  main:
    web-application-type: none
