version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb-pap
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongousr
      - MONGO_INITDB_ROOT_PASSWORD=mon35G00

volumes:
  data: {}

networks:
  default:
    name: mongodb_network